### PR TITLE
Add NodeOptions constructor to Cell

### PR DESCRIPTION
**Pull request by eeberhard**
* Add constructor declaration and
definition for Cell to take a
NodeOptions structure and parse
the name and period. This is
so that the Cell can be configured
as a component.

* Add utilities header to make parsing
NodeOptions more convenient. This utility
can be used by derived classes outside
of modulo core.

### CODE REVIEW

**Review by buschbapti — APPROVED** [review]
This looks good an handy!

**Comment by buschbapti** [comment]
I see there are some docstrings missing. Otherwise seems good like this. Do you know if the namespace is something used out of the box or should the cell actually use it and take it as argument?

**Comment by eeberhard** [comment]
> Do you know if the namespace is something used out of the box or should the cell actually use it and take it as argument?

I added the namespace parsing in case we want to extract the namespace from the NodeOption outside of construction for whatever reason. When a node or a lifecycle node is constructed, it will actually use the remapping argument if it is present to qualify the full node name. Now that you mention it though, the Cell will not support remapping if I don't also pass the option struct through to the underlying constructor... I guess I'll add that.

**Comment by eeberhard** [comment]
> I see there are some docstrings missing.

@buschbapti could you point out where docstrings are missing?

**Comment by buschbapti** [comment]
Sorry my bad it is alright

**Comment by buschbapti** [comment]
I was just looking at the `@param` or `@return` that do not have description. But maybe they did need one. I just always put something even if a bit redundant.

**Review by buschbapti — APPROVED** [review]

**Pull request merged**
