### PR TITLE
Fix test actions and workflows

### PR DESCRIPTION
**Pull request by domire8**
Our test pipeline is still trying to test the code on a `galactic-devel` base image, but this doesn't exist anymore. It's humble now.

### CODE REVIEW

**Review by eeberhard — APPROVED** [review]

**Comment by eeberhard** [comment]
Although now that I think about it, will the Galactic build and test fail after #146 ? Maybe now is also the time to remove that test entirely

**Comment by eeberhard** [comment]
I was too slow with my realisation :(

**Comment by domire8** [comment]
It's always going to fail yeah but it's not required and if we need to commit on the galactic branch (unlikely) we would still have that test

**Comment by eeberhard** [comment]
Ah that's right, it's not required to pass. I remember the discussion we had a while ago about that.

**Pull request merged**
